### ISSUE TITLE
[User-Story] Als Nutzer möchte ich die Profile anderer Nutzer anschauen können, um mich über die Person, ihre Bewertungen und ihre Erfahrungen informieren zu können

### ISSUE THREAD

**Issue by Schniggelz** [wrth1337/MyCargonaut#13]
# Overview
Als Nutzer möchte ich die Profile anderer Nutzer anschauen können, um mich über die Person, ihre Bewertungen und ihre Erfahrungen informieren zu können.

# Subtasks
- [ ] Task 1
- [ ] Taks 2

**Comment by wrth1337** [comment]
Wurde von @Schniggelz in #216 bearbeitet und gemerged.
