### ISSUE TITLE
[User-Story] Als Suchende möchte ich bei der Anfrage angeben, wie viele Sitze benötigt werden.

### ISSUE THREAD

**Issue by wrth1337** [wrth1337/MyCargonaut#18]
# Overview
Als Suchende möchte ich bei der Anfrage angeben, wie viele Sitze benötigt werden.

# Subtasks
- [ ] Task 1
- [ ] Taks 2

**Comment by marcel951** [comment]
wurde von @Schniggelz in #154 gelöst
