### ISSUE TITLE
[User-Story] Als User möchte ich ein Angebot/Gesuch buchen können, um den Zuschlag dazu zu erhalten

### ISSUE THREAD

**Issue by JonathanRech** [wrth1337/MyCargonaut#191]
# Overview
- Auf Abgebot / Gesuch zusagen (mit confirmation)
- Zahlungsvorgang 
- Freie Plätze / Ladung etc berechnen
-> Buchungen nur möglich, wenn noch Platz / Gesuch noch nicht angenommen
-> Nicht bei sich selbst buchen können
- Enge Verbindung mit Tracking 
-> Status nach Buchung anpassen etc 

# Subtasks
- [ ] Frontend
- [ ] Backend

**Comment by wrth1337** [comment]
Im Verlaufe der Entwicklung haben wir uns dazu entschieden, die Angebote in der Chat-Komponente anzuzeigen.

**Comment by wrth1337** [comment]
Generell wird der Status neu designed. Die aktuelle Darstellung in der Datenbank ist weder normalisiert noch anwendbar.
Lösung -> Redesign
