### ISSUE TITLE
[User-Story] Als Anfragende möchte ich weitere Informationen hinzufügen, wie "Richte mich nach meinen Mitfahrern" oder "höre gerne Musik".

### ISSUE THREAD

**Issue by wrth1337** [wrth1337/MyCargonaut#21]
# Overview
Als Anfragende möchte ich weitere Informationen hinzufügen, wie "Richte mich nach meinen Mitfahrern" oder "höre gerne Musik".

# Subtasks
- [ ] Task 1
- [ ] Taks 2

**Comment by marcel951** [comment]
wurde von @Schniggelz in #200 gelöst
