### ISSUE TITLE
Frontend: Sprache vereinheitlichen

### ISSUE THREAD

**Issue by hannafeddersen** [wrth1337/MyCargonaut#212]
# Sprache nicht konsistent
Die Sprache im Frontend ist nicht konsistent Deutsch oder Englisch. Anpassung der englischen Wörter auf Deutsch. 

- [ ] Anmeldung: Password -> Passwort
- [ ] Ábmelden: Text
- [ ] weitere möglich

**Comment by wrth1337** [comment]
Wurde in aktuellen polish-branches gefixt und wird daher geschlossen.
