### ISSUE TITLE
[User-Story] Als Suchender möchte ich angeben können, ob der Fahrer Nichtraucher sein soll

### ISSUE THREAD

**Issue by Schniggelz** [wrth1337/MyCargonaut#23]
# Overview
Als Suchender möchte ich angeben können, ob der Fahrer Nichtraucher sein soll.

# Subtasks
- [ ] Task 1
- [ ] Taks 2

**Comment by wrth1337** [comment]
Wurde von @Schniggelz in #154 bearbeitet und gemerged.
