### ISSUE TITLE
Teststrategie festlegen

### ISSUE THREAD

**Issue by wrth1337** [wrth1337/MyCargonaut#32]

**Comment by JonathanRech** [comment]
# Teststrategie 
Jede Funktion wird in sofern sinnvoll umsetzbar mit Unittests getestet. Dies gilt für sowohl Front- als auch Backend. Im Frontend wird Jasmin/Karma mit der Angular Integration genutzt, Im Backend wird Jest verwendet. Zu jeder sinnvoll zu testenden Funktion sollten mindestens zwei Unittests geschrieben werden, welche die korrekte Funktionalität der jeweiligen Funktion sicherstellen.
